steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cloud-5409/cloud-a3-artifact-repo/container1-img', '.']
  - name: 'gcr.io/cloud-builders/kubectl'
    env: ['CLOUDSDK_COMPUTE_REGION=us-central1', 'CLOUDSDK_CONTAINER_CLUSTER=cloud-5409-a3-gke-cluster']
    args: [ 'apply', '-f', 'volume.yaml' ]
  - name: 'gcr.io/cloud-builders/kubectl'
    env: [ 'CLOUDSDK_COMPUTE_REGION=us-central1', 'CLOUDSDK_CONTAINER_CLUSTER=cloud-5409-a3-gke-cluster' ]
    args: [ 'delete', 'deployment', 'container1-deployment', '--ignore-not-found' ]
  - name: 'gcr.io/cloud-builders/kubectl'
    env: ['CLOUDSDK_COMPUTE_REGION=us-central1', 'CLOUDSDK_CONTAINER_CLUSTER=cloud-5409-a3-gke-cluster']
    args: [ 'apply', '-f', 'deployment.yaml', '--force' ]


#  - name: 'gcr.io/cloud-builders/gke-deploy'
#    args:
#      - run
#      - --filename=pvc.yaml
#      - --location=us-central1
#      - --cluster=cloud-5409-a3-gke-cluster
#  - name: 'gcr.io/cloud-builders/gke-deploy'
#    args:
#      - run
#      - --filename=deployment.yaml
#      - --location=us-central1
#      - --cluster=cloud-5409-a3-gke-cluster

#  - name: 'gcr.io/cloud-builders/gke-deploy'
#    args: [ 'apply', '-f', 'pv.yaml' ]
#  - name: 'gcr.io/cloud-builders/gke-deploy'
#    args: [ 'apply', '-f', 'pvc.yaml' ]
#  - name: 'gcr.io/cloud-builders/gke-deploy'
#    args: [ 'apply', '-f', 'deployment.yaml' ]
images:
  - 'us-central1-docker.pkg.dev/cloud-5409/cloud-a3-artifact-repo/container1-img'

