AWSTemplateFormatVersion: "2010-09-09"

Resources:
  BeanstalkApplication:
    Type: "AWS::ElasticBeanstalk::Application"
    Properties:
      ApplicationName: EBS-T1
      Description: "AWS Elastic Beanstalk Application"

  BeanstalkApplicationVersion:
    Type: "AWS::ElasticBeanstalk::ApplicationVersion"
    Properties:
      ApplicationName: !Ref BeanstalkApplication
      Description: "Application Version 1.0"
      SourceBundle:
        S3Bucket: cloud-term-bucket
        S3Key: frontend.zip

  BeanstalkEnvironment:
    Type: "AWS::ElasticBeanstalk::Environment"
    Properties:
      ApplicationName: !Ref BeanstalkApplication
      Description: "Elastic Beanstalk Environment"
      VersionLabel: !Ref BeanstalkApplicationVersion
      SolutionStackName: "64bit Amazon Linux 2 v3.5.9 running Docker"
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Sub "arn:aws:iam::${AWS::AccountId}:instance-profile/LabInstanceProfile"
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: "1"
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: "3"
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: "t3.small"
        # - Namespace: aws:elasticbeanstalk:application:environment
        #   OptionName: DOCKER_IMAGE
        #   Value: "shubhammishra10/elb:latest"

  # CloudFrontDistribution:
  #   Type: "AWS::CloudFront::Distribution"
  #   Properties:
  #     DistributionConfig:
  #       Origins:
  #         - DomainName: !GetAtt BeanstalkEnvironment.EndpointURL
  #           Id: !Ref BeanstalkEnvironment
  #           CustomOriginConfig:
  #             HTTPPort: 80
  #             HTTPSPort: 443
  #             OriginProtocolPolicy: http-only
  #       DefaultCacheBehavior:
  #         TargetOriginId: !Ref BeanstalkEnvironment
  #         ForwardedValues:
  #           QueryString: false
  #         ViewerProtocolPolicy: redirect-to-https
  #       Enabled: true

Outputs:
  EnvironmentURL:
    Description: "URL of the Elastic Beanstalk Environment"
    Value: !Sub "http://${BeanstalkEnvironment.EndpointURL}"

  # CloudFrontDistributionURL:
  #   Description: "URL of the CloudFront distribution"
  #   Value: !Sub "https://${CloudFrontDistribution.DomainName}"
