AWSTemplateFormatVersion: "2010-09-09"

Resources:
  UsersTable:
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: Retain
    Properties:
      TableName: "users"
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  SentimentDataTableArn:
    Description: "ARN of the users DynamoDB table"
    Value: !Ref UsersTable