AWSTemplateFormatVersion: "2010-09-09"

Resources:
  LambdaFunctionRegister:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: register
      Runtime: nodejs14.x
      Handler: register.handler
      Code:
        S3Bucket: cloud-term-bucket
        S3Key: register.zip
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
  
  LambdaFunctionLogin:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: login
      Runtime: nodejs14.x
      Handler: login.handler
      Code:
        S3Bucket: cloud-term-bucket
        S3Key: login.zip
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"

  LambdaFunctionTextract:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: textract
      Runtime: nodejs14.x
      Handler: textract.handler
      Code:
        S3Bucket: cloud-term-bucket
        S3Key: textract.zip
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
  
  LambdaFunctionRekognition:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: rekognition
      Runtime: nodejs14.x
      Handler: rekognition.handler
      Code:
        S3Bucket: cloud-term-bucket
        S3Key: rekognition.zip
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
