AWSTemplateFormatVersion: "2010-09-09"

Resources:
  LambdaFunction1:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: lambda1
      Runtime: nodejs14.x
      Handler: lambda1.handler
      Code:
        S3Bucket: cloud-term-bucket
        S3Key: lambda1.zip
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"

  LambdaFunctionTextract:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: textract
      Runtime: nodejs14.x
      Handler: textract.handler
      Code:
        S3Bucket: cloud-term-bucket
        S3Key: textract.zip
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
