version: "3"
services:
  flask1:
    image: shubhammishra10/flask1
    container_name: flask1
    ports:
      - 6000:6000
    volumes:
      - .:/usr/src/app/host_vol
  flask2:
    image: shubhammishra10/flask2
    container_name: flask2
    ports:
      - 6003:6003
    volumes:
      - .:/usr/src/app/host_vol
#volumes:
#  shared_volume:
