services:
  flask1:
    image: shubhammishra10/flask1
    container_name: flask1
    ports:
      - 6000:6000
    networks:
      - shubhammishra10network
    volumes:
      - .:/usr/src/app/host_vol
  flask2:
    image: shubhammishra10/flask2
    container_name: flask2
    ports:
      - 6003:6003
    networks:
      - shubhammishra10network
    volumes:
      - .:/usr/src/app/host_vol
networks:
  shubhammishra10network:
    driver: bridge
