version: "3"
services:
  flask1:
    image: shubhammishra10/flask1v1
    container_name: flask1
#    environment:
#      - discovery.type=single-node
    ports:
      - 6000:6000
    volumes:
      - ./flask1:/app
  flask2:
    image: shubhammishra10/flask2v1
    container_name: flask2
    ports:
      - 6003:6003
    volumes:
      - ./flask2:/app
#volumes:
#  - ./:/app
